version: '3'
services:
  mongodb-service:
    image: mongo
    container_name: mongodb-service
    ports:
      - 27017:27017
    networks:
      - mongodb-network
    volumes:
      - vlm:/mongodb 
  backend:
    image: app-back
    container_name: backend
    ports:
      - 5001:5001
    depends_on:
      - mongodb-service
    networks:
      - mongodb-network
  frontend:
    image: app-front
    container_name: frontend
    ports:
      - 3000:80
    networks:
      - mongodb-network
    depends_on:
      - backend
volumes:
  vlm:
networks:
  mongodb-network:
   driver: bridge